module.exports = [
  {
    name: 'Breitenbush River',
    id: '14179000',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'Sandy River',
    id: '14142500',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river'
  },
  {
    name: 'Hood River at Tucker Bridge',
    id: '14120000',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'Illinois River',
    id: '14377100',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'Chetco River',
    id: '14400000',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'North Santiam (Boulder)',
    id: '14178000',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'East Fork of the Lewis (Heissen)',
    id: '14222500',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },
  {
    name: 'Canyon Creek',
    id: '14219000',
    isHidden: false,
    cfs: '',
    time: '',
    desc: 'Cool river',
  },

];
